### ISSUE TITLE
Overhead of Python Conversion

### ISSUE THREAD

**Issue by cortner** [libAtoms/Atoms.jl#1]
Here are two ways to get the local neighbour information from ASE's neighbourlist:

```
# Standard call: 0.356330 seconds (89.00 k allocations: 3.258 MB)
@time for n = 1:500 I, off = nlist.po[:get_neighbors](0); end   
# just get a PyObject: 0.042462 seconds (9.50 k allocations: 273.438 KB)
@time for n = 1:500 ret = pycall(nlist.po[:get_neighbors], PyObject, 0); end
```

The first one makes some automatic conversions, the second one makes no conversion at all. This shows there is a lot of overhead. Can it be reduced or avoided altogether?

**Comment by cortner** [comment]
a potentially easy fix (?) would be to use the pure C interface to matscipy ?

**Comment by jameskermode** [comment]
Closing issue as matscipy does not require conversion of each atoms' neighbours, just a one-off conversion of the whole list of pairs, so this will not be a problem.
